# Generated by Django 3.0.1 on 2019-12-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191223_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_data_id',
            new_name='user',
        ),
    ]
